name: Create a new .NET library

on:
  workflow_dispatch:
    inputs:
      NewRepoName:
        description: "Name of the new repository"
        required: true
      NewProjectName:
        description: "Name of the new project"
        required: true
      GitHubOrg:
        description: "GitHub organization name"
        required: true
        default: "Somasundar-Projects"
      TargetFrameworks:
        description: "Target frameworks"
        required: true
        default: "net8.0;net9.0"

env:
  GH_TOKEN: ${{ secrets.GH_PAT_TOKEN }}

jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PowerShell script
        shell: pwsh
        working-directory: ./Scripts
        run: |
          .\Dotnet.Library.ps1 -NewRepoName "${{ github.event.inputs.NewRepoName }}" -NewProjectName "${{ github.event.inputs.NewProjectName }}" -GitHubOrg "${{ github.event.inputs.GitHubOrg }}" -TemplateRepo "Somasundar-Projects/DevOps" -TargetFrameworks "${{ github.event.inputs.TargetFrameworks }}" -GitHubUser "${{ github.actor }}"
